

services:
  # Development-specific overrides for API
  api:
    environment:
      NODE_ENV: development
      DEBUG: true
      LOG_LEVEL: debug
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Development-specific overrides for Frontend
  frontend:
    environment:
      NODE_ENV: development
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.expo
    command: npm start

  # Development database with more verbose logging
  postgres:
    environment:
      POSTGRES_DB: recipix_dev
      POSTGRES_USER: recipix_user
      POSTGRES_PASSWORD: recipix_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"

  # Development Redis with persistence disabled for faster startup
  redis:
    command: redis-server --appendonly no --save ""
